#!/usr/bin/env python

import sys
import os
import re
import argparse
import configparser
import collections
import json
from git import Repo
import requests

url = None
headers = None
change_id_re = r"Change-Id: (.+?)(\s|$)"
dry_run = False


class bcolors:
    HEADER = '\033[95m'
    OKBLUE = '\033[94m'
    OKCYAN = '\033[96m'
    OKGREEN = '\033[92m'
    WARNING = '\033[93m'
    FAIL = '\033[91m'
    ENDC = '\033[0m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'


def load_gitreview_config(remote, root_dir):
    global url
    global headers
    config = configparser.ConfigParser()
    config.read(os.path.join(root_dir, ".gitreview"))
    configs = config[remote]
    host = configs["host"]
    project_id = configs["project_id"]
    private_token = configs["private_token"]
    url = "{}/api/v4/projects/{}/merge_requests".format(host, project_id)
    headers = {"PRIVATE-TOKEN": private_token}


def get_msg_title_description(msg):
    title, desc = tuple(msg.split("\n", 1))
    desc = re.sub(change_id_re, "", desc)
    return title, desc


def get_change_id(msg):
    m = re.search(change_id_re, msg)
    if m:
        return m.group(1)
    else:
        raise ValueError("Didn't find the Change-Id in the commit message!")


def get_remote_branch_name(local_branch, change_id):
    return "{}-{}".format(local_branch, change_id[1:5])


def is_remote_stale(commits, remote_commits):
    """Checks if remote becomes stale due to local changes."""
    shas = set([c.hexsha for c in commits])
    remote_shas = set([c.hexsha for c in remote_commits])
    return shas != remote_shas


def get_merge_request(branch):
    """Return a `MergeRequest` given branch name."""
    r = requests.get("{}?state=opened".format(url), headers=headers)
    for mr in r.json():
        if mr["source_branch"] == branch:
            return MergeRequest(json_data=mr)
    return None


class MergeRequest:

    def __init__(
            self, source_branch=None, target_branch=None, title=None,
            description=None, json_data=None):
        self._source_branch = source_branch
        self._target_branch = target_branch
        self._title = title
        self._description = description
        self._iid = None
        self._web_url = None
        self._mergeable = False

        if json_data is not None:
            for attr in json_data:
                setattr(self, "_{}".format(attr), json_data[attr])

        self._local_branch = self._source_branch.rsplit("-", 1)[0]

    @property
    def mergeable(self):
        return self._mergeable

    @property
    def source_branch(self):
        return self._source_branch

    def print_info(self, verbose=False):
        print("* {} {}".format(self._web_url, self._title))
        if verbose:
            print(
                "    {} {} -> {} ({})".format(
                    "[new branch]" if self._iid is None else "[updated]",
                    self._local_branch, self._source_branch,
                    self._target_branch))

    def create(self):
        data = {
            "source_branch": self._source_branch,
            "target_branch": self._target_branch,
            "title": self._title,
            "description": self._description,
        }
        r = requests.post(url, headers=headers, data=data)
        if r.status_code != requests.codes.ok:
            r.raise_for_status()
        data = r.json()
        self._iid = data["iid"]
        self._web_url = data["web_url"]

    def update(
            self, source_branch=None, target_branch=None, title=None,
            description=None):
        if source_branch is not None:
            self._source_branch = source_branch
        if target_branch is not None:
            self._target_branch = target_branch
        if title is not None:
            self._title = title
        if description is not None:
            self._description = description
        data = {
            "source_branch": self._source_branch,
            "target_branch": self._target_branch,
            "title": self._title,
            "description": self._description,
        }
        r = requests.put(
            "{}/{}".format(url, self._iid), headers=headers, data=data)
        if r.status_code != requests.codes.ok:
            r.raise_for_status()
        data = r.json()
        self._iid = data["iid"]
        self._web_url = data["web_url"]

    def submit(self):
        if self._iid is None:
            raise ValueError("Must set iid before submittng an MR!")
        r = requests.put("{}/{}/merge".format(url, self._iid), headers=headers)
        if r.status_code != requests.codes.ok:
            r.raise_for_status()

    def delete(self):
        if self._iid is None:
            raise ValueError("Must set iid before deleting an MR!")
        r = requests.delete("{}/{}".format(url, self._iid), headers=headers)
        if r.status_code != requests.codes.ok:
            r.raise_for_status()


def submit_merge_requests(local_branch):
    """Submits merge requests."""

    # Get MRs created off of the given branch.
    r = requests.get("{}?state=opened".format(url), headers=headers)
    mrs = collections.OrderedDict()
    for json_data in r.json():
        if json_data["source_branch"].startswith(local_branch):
            mrs[json_data["target_branch"]] = MergeRequest(json_data=json_data)
    if len(mrs) == 0:
        print("No MRs found for this branch: {}".format(local_branch))
        return
    for mr in mrs.values():
        mr.print_info()
        print("    [mergeable]: {}".format(mr.mergeable))

    def find_mergeable_chain(mrs, root):
        if not root.mergeable:
            return []
        else:
            mergeables = [root]
            if root.source_branch not in mrs:
                return mergeables
            else:
                next_mr = mrs[root.source_branch]
                mergeables.extend(find_mergeable_chain(mrs, next_mr))
                return mergeables

    root = mrs["master"]
    mergeables = find_mergeable_chain(mrs, root)
    if len(mergeables) == 0:
        print("No MRs are currently mergeable.")
        return

    # We must submit MRs from the oldest. And before submitting an MR, we must
    # change its target_branch to master.
    for mr in mergeables:
        if not dry_run:
            mr.update(target_branch="master")
            #FIXME: Poll the merge req status and waiting until merge_status is
            # no longer "checking".
            mr.submit()

    print()
    print(bcolors.OKGREEN + "SUCCESS" + bcolors.ENDC)
    print()
    print("{} MR(s) submitted at {}:".format(len(mrs), remote.url))
    for mr in mergeables:
        mr.print_info()


def create_merge_requests(repo, remote, local_branch):
    """Creates new merge requests on remote."""

    # Sync up remote branches.
    remote.fetch(prune=True)

    # Get the local commits that are ahead of the origin/master.
    commits = list(repo.iter_commits("origin/master..{}".format(local_branch)))
    commits.reverse()

    # Push the commits to remote by creating a new branch for each.
    remote_branches = {}
    for c in commits:
        change_id = get_change_id(c.message)
        remote_branch = get_remote_branch_name(local_branch, change_id)
        remote.push(
            refspec="{}:refs/heads/{}".format(c.hexsha, remote_branch),
            force=True)
        remote_branches[c.hexsha] = remote_branch

    # Create a merge request for each commit.
    mrs = []
    for idx, c in enumerate(commits):
        change_id = get_change_id(c.message)
        source_branch = remote_branches[c.hexsha]
        if idx == 0:
            # If this is the oldest commit, then the target branch should be
            # master.
            target_branch = "master"
        else:
            target_branch = remote_branches[commits[idx - 1].hexsha]
        title, desp = get_msg_title_description(c.message)
        mr = get_merge_request(source_branch)
        if mr is not None:
            mr.update(
                source_branch=source_branch, target_branch=target_branch,
                title=title, description=desp)
        else:
            mr = MergeRequest(
                source_branch=source_branch, target_branch=target_branch,
                title=title, description=desp)
            mr.create()
        mrs.append(mr)
    print()
    print(bcolors.OKGREEN + "SUCCESS" + bcolors.ENDC)
    print()
    print("New Changes:")
    for mr in mrs:
        mr.print_info(verbose=True)
    print("To {}".format(remote.url))


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "remote", type=str, nargs="?", default="origin",
        help="The remote to push the reviews.")
    parser.add_argument(
        "local_branch", type=str, nargs="?",
        help="The local branch to be reviewed.")
    parser.add_argument(
        "--merge", "-m", action="store_true", default=False,
        help="Merge the MRs if they are approved.")
    parser.add_argument(
        "--dry-run", "-d", action="store_true", default=False,
        help="Dry run the command.")
    args = parser.parse_args()

    repo = Repo(os.getcwd(), search_parent_directories=True)
    load_gitreview_config(args.remote, repo.git.rev_parse("--show-toplevel"))
    local_branch = args.local_branch
    if args.local_branch is None:
        local_branch = repo.active_branch.name

    global dry_run
    dry_run = args.dry_run
    if dry_run:
        print(
            bcolors.WARNING + "warning" + bcolors.ENDC + ": Dry running mode.")

    # Submit the MRs if they become mergeable.
    if args.merge:
        print("Submitting merge requests:")
        submit_merge_requests(local_branch)
        sys.exit(0)

    remote = repo.remote(name=args.remote)
    create_merge_requests(repo, remote, local_branch)


if __name__ == "__main__":
    main()
